sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

 # Configurazione delle classi admin
sonata_admin.event:
    class: App\Admin\EventAdmin
    tags:
         - { name: sonata.admin, manager_type: orm, group: sonata.admin.group.content, label: 'Event' }
    arguments:
            - ~
            - App\Entity\Event
            - ~
    calls:
            - [ setTranslationDomain, [AppBundle]]


sonata_admin:
    title: 'Admin'
    security:
        handler: sonata.admin.security.handler.noop

    # Definizione dei percorsi per i file dei servizi admin
    dashboard:
        groups:
            sonata.admin.group.content:
                label: 'Content'
                items:
                    - sonata.admin.post
                    # Aggiungi altri admin qui, se necessario

   
    # Configurazione del routing
    templates:
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
        layout:   '@SonataAdmin/standard_layout.html.twig'
        user_block: '@SonataAdmin/Core/user_block.html.twig'