sonata_block:
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]


sonata_admin:
   
    # Configurazione del routing
    templates:
        preview: '@SonataAdmin/CRUD/preview.html.twig'
        dashboard: '@SonataAdmin/Core/dashboard.html.twig'
        layout:   '@SonataAdmin/standard_layout.html.twig'
        user_block: '@SonataAdmin/Core/user_block.html.twig'
        ajax:    '@SonataAdmin/ajax_layout.html.twig'

        # default value if done set, actions templates, should extend global templates
        list:    '@SonataAdmin/CRUD/list.html.twig'
        show:    '@SonataAdmin/CRUD/show.html.twig'
        edit:    '@SonataAdmin/CRUD/edit.html.twig'