vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        event_cover:
            uri_prefix: /images/event_cover
            upload_destination: '%kernel.project_dir%/public/images/event_cover'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
