# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        event_cover:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/event_cover'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer