version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    networks:
      - postgres
    ports:
      - "5432:5432"
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    restart: on-failure
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"
###< symfony/mailer ###

networks:
###> doctrine/doctrine-bundle ###
  postgres:
    driver: bridge
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  postgres:
  pgadmin:
###< doctrine/doctrine-bundle ###
